---
- name: "Load user class variables"
  include_vars: "{{ class }}.yml"

- name: "Add groups for class {{ class }}"
  group:
    name: "{{ item.key }}"
    state: "{{ item.value.state | default('present') }}"
    gid: "{{ item.value.gid }}"
  with_dict: "{{ GROUPS }}"

- name: "Set up sudo access for groups"
  lineinfile:
    dest: /etc/sudoers
    regexp: '^%{{ item.key }}'
    line: '%{{ item.key }} ALL=(ALL) NOPASSWD: ALL'
    state: "{% if item.value.sudo | default(False) | bool() %}present{% else %}absent{% endif %}"
  with_dict: "{{ GROUPS }}"

- name: "Run play to create users"
  include: user_tasks.yml ENTRIES={{ USERS }}
